# Copyright (c) 2025, Servio and contributors
# For license information, please see license.txt

import frappe


def after_install():
	setup_defaults()


def setup_defaults():
	set_payroll_settings_defaults()
	create_salary_components()


def set_payroll_settings_defaults():
	"""
	Set default Payroll Settings for PH payroll setup.
	Runs only once on fresh install — does not override user changes on migrate.
	"""
	settings = frappe.get_single("Payroll Settings")

	settings.payroll_based_on = "Attendance"
	settings.consider_unmarked_attendance_as = "Absent"


	settings.save(ignore_permissions=True)
	frappe.db.commit()


def create_salary_components():
	"""
	Create default PH salary components on fresh install.
	Skips existing components — does not override user changes on migrate.
	"""
	components = _get_salary_components()

	for data in components:
		name = data.get("name")

		if frappe.db.exists("Salary Component", name):
			continue  # already exists, skip

		doc = frappe.new_doc("Salary Component")
		doc.update(data)
		doc.insert(ignore_permissions=True)

	frappe.db.commit()


def _get_salary_components():
	return [
		{
			"name": "PH - REG",
			"salary_component": "PH - REG",
			"salary_component_abbr": "PH_REG",
			"type": "Earning",
			"formula": "working_hours * hourly_rate",
			"amount_based_on_formula": 1,
			"formula_based_on_attendance": 1,
			"formula_effectivity": "Period",
			"condition": "not rest_day and not special_holiday and not legal_holiday",
			"is_tax_applicable": 1,
			"is_basic_pay": 1,
			"is_13th_month_pay_applicable": 1,
			"depends_on_payment_days": 0,
		},
		{
			"name": "PH - REG_OT",
			"salary_component": "PH - REG_OT",
			"salary_component_abbr": "PH_REG_OT",
			"type": "Earning",
			"formula": "overtime * hourly_rate * 1.25",
			"amount_based_on_formula": 1,
			"formula_based_on_attendance": 1,
			"formula_effectivity": "Period",
			"condition": "not rest_day and not special_holiday and not legal_holiday",
			"is_tax_applicable": 1,
			"is_basic_pay": 0,
			"is_13th_month_pay_applicable": 1,
			"depends_on_payment_days": 0,
		},
		{
			"name": "PH - ND",
			"salary_component": "PH - ND",
			"salary_component_abbr": "PH_ND",
			"type": "Earning",
			"formula": "night_differential * hourly_rate * 0.1",
			"amount_based_on_formula": 1,
			"formula_based_on_attendance": 1,
			"formula_effectivity": "Period",
			"condition": "not rest_day and not special_holiday and not legal_holiday",
			"is_tax_applicable": 1,
			"is_basic_pay": 0,
			"is_13th_month_pay_applicable": 1,
			"depends_on_payment_days": 0,
		},
		{
			"name": "PH - ND_OT",
			"salary_component": "PH - ND_OT",
			"salary_component_abbr": "PH_ND_OT",
			"type": "Earning",
			"formula": "night_differential_overtime * hourly_rate * 1.25 * 0.1",
			"amount_based_on_formula": 1,
			"formula_based_on_attendance": 1,
			"formula_effectivity": "Period",
			"condition": "not rest_day and not special_holiday and not legal_holiday",
			"is_tax_applicable": 1,
			"is_basic_pay": 0,
			"is_13th_month_pay_applicable": 1,
			"depends_on_payment_days": 0,
		},
		{
			"name": "PH - RST",
			"salary_component": "PH - RST",
			"salary_component_abbr": "PH_RST",
			"type": "Earning",
			"formula": "working_hours * hourly_rate * 1.3",
			"amount_based_on_formula": 1,
			"formula_based_on_attendance": 1,
			"formula_effectivity": "Period",
			"condition": "rest_day and not special_holiday and not legal_holiday",
			"is_tax_applicable": 1,
			"is_basic_pay": 0,
			"is_13th_month_pay_applicable": 1,
			"depends_on_payment_days": 0,
		},
		{
			"name": "PH - RST_OT",
			"salary_component": "PH - RST_OT",
			"salary_component_abbr": "PH_RST_OT",
			"type": "Earning",
			"formula": "overtime * hourly_rate * 1.69",
			"amount_based_on_formula": 1,
			"formula_based_on_attendance": 1,
			"formula_effectivity": "Period",
			"condition": "rest_day and not special_holiday and not legal_holiday",
			"is_tax_applicable": 1,
			"is_basic_pay": 0,
			"is_13th_month_pay_applicable": 1,
			"depends_on_payment_days": 0,
		},
		{
			"name": "PH - RST_ND",
			"salary_component": "PH - RST_ND",
			"salary_component_abbr": "PH_RST_ND",
			"type": "Earning",
			"formula": "night_differential * hourly_rate * 1.3 * 0.1",
			"amount_based_on_formula": 1,
			"formula_based_on_attendance": 1,
			"formula_effectivity": "Period",
			"condition": "rest_day and not special_holiday and not legal_holiday",
			"is_tax_applicable": 1,
			"is_basic_pay": 0,
			"is_13th_month_pay_applicable": 1,
			"depends_on_payment_days": 0,
		},
		{
			"name": "PH - RST_ND_OT",
			"salary_component": "PH - RST_ND_OT",
			"salary_component_abbr": "PH_RST_ND_OT",
			"type": "Earning",
			"formula": "night_differential_overtime * hourly_rate * 1.3 * 0.1",
			"amount_based_on_formula": 1,
			"formula_based_on_attendance": 1,
			"formula_effectivity": "Period",
			"condition": "rest_day and not special_holiday and not legal_holiday",
			"is_tax_applicable": 1,
			"is_basic_pay": 0,
			"is_13th_month_pay_applicable": 1,
			"depends_on_payment_days": 0,
		},
		{
			"name": "PH - SP",
			"salary_component": "PH - SP",
			"salary_component_abbr": "PH_SP",
			"type": "Earning",
			"formula": "working_hours * hourly_rate * 1.3",
			"amount_based_on_formula": 1,
			"formula_based_on_attendance": 1,
			"formula_effectivity": "Period",
			"condition": "not rest_day and special_holiday and not legal_holiday",
			"is_tax_applicable": 1,
			"is_basic_pay": 0,
			"is_13th_month_pay_applicable": 1,
			"depends_on_payment_days": 0,
		},
		{
			"name": "PH - SP_OT",
			"salary_component": "PH - SP_OT",
			"salary_component_abbr": "PH_SP_OT",
			"type": "Earning",
			"formula": "overtime * hourly_rate * 1.69",
			"amount_based_on_formula": 1,
			"formula_based_on_attendance": 1,
			"formula_effectivity": "Period",
			"condition": "not rest_day and special_holiday and not legal_holiday",
			"is_tax_applicable": 1,
			"is_basic_pay": 0,
			"is_13th_month_pay_applicable": 1,
			"depends_on_payment_days": 0,
		},
		{
			"name": "PH - SP_ND",
			"salary_component": "PH - SP_ND",
			"salary_component_abbr": "PH_SP_ND",
			"type": "Earning",
			"formula": "night_differential * hourly_rate * 1.3 * 0.1",
			"amount_based_on_formula": 1,
			"formula_based_on_attendance": 1,
			"formula_effectivity": "Period",
			"condition": "not rest_day and special_holiday and not legal_holiday",
			"is_tax_applicable": 1,
			"is_basic_pay": 0,
			"is_13th_month_pay_applicable": 1,
			"depends_on_payment_days": 0,
		},
		{
			"name": "PH - SP_ND_OT",
			"salary_component": "PH - SP_ND_OT",
			"salary_component_abbr": "PH_SP_ND_OT",
			"type": "Earning",
			"formula": "night_differential_overtime * hourly_rate * 1.3 * 0.1",
			"amount_based_on_formula": 1,
			"formula_based_on_attendance": 1,
			"formula_effectivity": "Period",
			"condition": "not rest_day and special_holiday and not legal_holiday",
			"is_tax_applicable": 1,
			"is_basic_pay": 0,
			"is_13th_month_pay_applicable": 1,
			"depends_on_payment_days": 0,
		},
		{
			"name": "PH - LEG",
			"salary_component": "PH - LEG",
			"salary_component_abbr": "PH_LEG",
			"type": "Earning",
			"formula": "working_hours * hourly_rate * 2",
			"amount_based_on_formula": 1,
			"formula_based_on_attendance": 1,
			"formula_effectivity": "Period",
			"condition": "not rest_day and not special_holiday and legal_holiday",
			"is_tax_applicable": 1,
			"is_basic_pay": 0,
			"is_13th_month_pay_applicable": 1,
			"depends_on_payment_days": 0,
		},
		{
			"name": "PH - LEG_OT",
			"salary_component": "PH - LEG_OT",
			"salary_component_abbr": "PH_LEG_OT",
			"type": "Earning",
			"formula": "overtime * hourly_rate * 2.6",
			"amount_based_on_formula": 1,
			"formula_based_on_attendance": 1,
			"formula_effectivity": "Period",
			"condition": "not rest_day and not special_holiday and legal_holiday",
			"is_tax_applicable": 1,
			"is_basic_pay": 0,
			"is_13th_month_pay_applicable": 1,
			"depends_on_payment_days": 0,
		},
		{
			"name": "PH - LEG_ND",
			"salary_component": "PH - LEG_ND",
			"salary_component_abbr": "PH_LEG_ND",
			"type": "Earning",
			"formula": "night_differential * hourly_rate * 2 * 0.1",
			"amount_based_on_formula": 1,
			"formula_based_on_attendance": 1,
			"formula_effectivity": "Period",
			"condition": "not rest_day and not special_holiday and legal_holiday",
			"is_tax_applicable": 1,
			"is_basic_pay": 0,
			"is_13th_month_pay_applicable": 1,
			"depends_on_payment_days": 0,
		},
		{
			"name": "PH - LEG_ND_OT",
			"salary_component": "PH - LEG_ND_OT",
			"salary_component_abbr": "PH_LEG_ND_OT",
			"type": "Earning",
			"formula": "night_differential_overtime * hourly_rate * 2 * 0.1",
			"amount_based_on_formula": 1,
			"formula_based_on_attendance": 1,
			"formula_effectivity": "Period",
			"condition": "not rest_day and not special_holiday and legal_holiday",
			"is_tax_applicable": 1,
			"is_basic_pay": 0,
			"is_13th_month_pay_applicable": 1,
			"depends_on_payment_days": 0,
		},
		{
			"name": "PH - SP_RST",
			"salary_component": "PH - SP_RST",
			"salary_component_abbr": "PH_SP_RST",
			"type": "Earning",
			"formula": "working_hours * hourly_rate * 1.5",
			"amount_based_on_formula": 1,
			"formula_based_on_attendance": 1,
			"formula_effectivity": "Period",
			"condition": "rest_day and special_holiday and not legal_holiday",
			"is_tax_applicable": 1,
			"is_basic_pay": 0,
			"is_13th_month_pay_applicable": 1,
			"depends_on_payment_days": 0,
		},
		{
			"name": "PH - SP_RST_OT",
			"salary_component": "PH - SP_RST_OT",
			"salary_component_abbr": "PH_SP_RST_OT",
			"type": "Earning",
			"formula": "overtime * hourly_rate * 1.95",
			"amount_based_on_formula": 1,
			"formula_based_on_attendance": 1,
			"formula_effectivity": "Period",
			"condition": "rest_day and special_holiday and not legal_holiday",
			"is_tax_applicable": 1,
			"is_basic_pay": 0,
			"is_13th_month_pay_applicable": 1,
			"depends_on_payment_days": 0,
		},
		{
			"name": "PH - SP_RST_ND",
			"salary_component": "PH - SP_RST_ND",
			"salary_component_abbr": "PH_SP_RST_ND",
			"type": "Earning",
			"formula": "night_differential * hourly_rate * 1.5 * 0.1",
			"amount_based_on_formula": 1,
			"formula_based_on_attendance": 1,
			"formula_effectivity": "Period",
			"condition": "rest_day and special_holiday and not legal_holiday",
			"is_tax_applicable": 1,
			"is_basic_pay": 0,
			"is_13th_month_pay_applicable": 1,
			"depends_on_payment_days": 0,
		},
		{
			"name": "PH - SP_RST_ND_OT",
			"salary_component": "PH - SP_RST_ND_OT",
			"salary_component_abbr": "PH_SP_RST_ND_OT",
			"type": "Earning",
			"formula": "night_differential_overtime * hourly_rate * 1.5 * 0.1",
			"amount_based_on_formula": 1,
			"formula_based_on_attendance": 1,
			"formula_effectivity": "Period",
			"condition": "rest_day and special_holiday and not legal_holiday",
			"is_tax_applicable": 1,
			"is_basic_pay": 0,
			"is_13th_month_pay_applicable": 1,
			"depends_on_payment_days": 0,
		},
		{
			"name": "PH - LEG_RST",
			"salary_component": "PH - LEG_RST",
			"salary_component_abbr": "PH_LEG_RST",
			"type": "Earning",
			"formula": "working_hours * hourly_rate * 2.6",
			"amount_based_on_formula": 1,
			"formula_based_on_attendance": 1,
			"formula_effectivity": "Period",
			"condition": "rest_day and not special_holiday and legal_holiday",
			"is_tax_applicable": 1,
			"is_basic_pay": 0,
			"is_13th_month_pay_applicable": 1,
			"depends_on_payment_days": 0,
		},
		{
			"name": "PH - LEG_RST_OT",
			"salary_component": "PH - LEG_RST_OT",
			"salary_component_abbr": "PH_LEG_RST_OT",
			"type": "Earning",
			"formula": "overtime * hourly_rate * 3.38",
			"amount_based_on_formula": 1,
			"formula_based_on_attendance": 1,
			"formula_effectivity": "Period",
			"condition": "rest_day and not special_holiday and legal_holiday",
			"is_tax_applicable": 1,
			"is_basic_pay": 0,
			"is_13th_month_pay_applicable": 1,
			"depends_on_payment_days": 0,
		},
		{
			"name": "PH - LEG_RST_ND",
			"salary_component": "PH - LEG_RST_ND",
			"salary_component_abbr": "PH_LEG_RST_ND",
			"type": "Earning",
			"formula": "night_differential * hourly_rate * 2.6 * 0.1",
			"amount_based_on_formula": 1,
			"formula_based_on_attendance": 1,
			"formula_effectivity": "Period",
			"condition": "rest_day and not special_holiday and legal_holiday",
			"is_tax_applicable": 1,
			"is_basic_pay": 0,
			"is_13th_month_pay_applicable": 1,
			"depends_on_payment_days": 0,
		},
		{
			"name": "PH - LEG_RST_ND_OT",
			"salary_component": "PH - LEG_RST_ND_OT",
			"salary_component_abbr": "PH_LEG_RST_ND_OT",
			"type": "Earning",
			"formula": "night_differential_overtime * hourly_rate * 2.6 * 0.1",
			"amount_based_on_formula": 1,
			"formula_based_on_attendance": 1,
			"formula_effectivity": "Period",
			"condition": "rest_day and not special_holiday and legal_holiday",
			"is_tax_applicable": 1,
			"is_basic_pay": 0,
			"is_13th_month_pay_applicable": 1,
			"depends_on_payment_days": 0,
		},
		{
			"name": "PH - Undertime",
			"salary_component": "PH - Undertime",
			"salary_component_abbr": "PH_UT",
			"type": "Earning",
			"formula": "undertime * -hourly_rate",
			"amount_based_on_formula": 1,
			"formula_based_on_attendance": 1,
			"formula_effectivity": "Period",
			"condition": "",
			"is_tax_applicable": 1,
			"is_basic_pay": 0,
			"is_13th_month_pay_applicable": 0,
			"depends_on_payment_days": 0,
		},
		{
			"name": "PH - Absence",
			"salary_component": "PH - Absence",
			"salary_component_abbr": "PH_A",
			"type": "Earning",
			"formula": "absent_days * -daily_rate",
			"amount_based_on_formula": 1,
			"formula_based_on_attendance": 0,
			"formula_effectivity": "Period",
			"condition": "",
			"is_tax_applicable": 1,
			"is_basic_pay": 0,
			"is_13th_month_pay_applicable": 0,
			"depends_on_payment_days": 0,
		},
		{
			"name": "PH - Leave",
			"salary_component": "PH - Leave",
			"salary_component_abbr": "PH_L",
			"type": "Earning",
			"formula": "leave * hourly_rate",
			"amount_based_on_formula": 1,
			"formula_based_on_attendance": 1,
			"formula_effectivity": "Period",
			"condition": "",
			"is_tax_applicable": 1,
			"is_basic_pay": 0,
			"is_13th_month_pay_applicable": 0,
			"depends_on_payment_days": 0,
		},
		{
			"name": "PH - REG (Fixed)",
			"salary_component": "PH - REG (Fixed)",
			"salary_component_abbr": "PH_REG_F",
			"type": "Earning",
			"formula": "(monthly_rate / 2) if total_working_days <= 16 else monthly_rate",
			"amount_based_on_formula": 1,
			"formula_based_on_attendance": 0,
			"formula_effectivity": "Period",
			"condition": "",
			"is_tax_applicable": 1,
			"is_basic_pay": 1,
			"is_13th_month_pay_applicable": 1,
			"depends_on_payment_days": 0,
		},
		{
			"name": "PH - 13th Month Pay",
			"salary_component": "PH - 13th Month Pay",
			"salary_component_abbr": "PH_13M_1",
			"type": "Earning",
			"formula": "ph_13th_month_pay()",
			"amount_based_on_formula": 1,
			"formula_based_on_attendance": 0,
			"formula_effectivity": "Period",
			"condition": "",
			"is_tax_applicable": 1,
			"is_basic_pay": 0,
			"is_13th_month_pay_applicable": 0,
			"depends_on_payment_days": 0,
		},
		# --- Deductions ---
		{
			"name": "PH - PHIC Contribution",
			"salary_component": "PH - PHIC Contribution",
			"salary_component_abbr": "PH_PHIC",
			"type": "Deduction",
			"formula": "max(250, (0.05 * basic_pay) * 0.5)",
			"amount_based_on_formula": 1,
			"formula_based_on_attendance": 0,
			"formula_effectivity": "Monthly",
			"statistical_component": 0,
			"is_tax_applicable": 1,
			"is_basic_pay": 0,
			"is_13th_month_pay_applicable": 0,
			"depends_on_payment_days": 0,
		},
		{
			"name": "PH - PHIC Employer Contribution",
			"salary_component": "PH - PHIC Employer Contribution",
			"salary_component_abbr": "PH_PHIC_ER",
			"type": "Deduction",
			"formula": "max(250, (0.05 * basic_pay) * 0.5)",
			"amount_based_on_formula": 1,
			"formula_based_on_attendance": 0,
			"formula_effectivity": "Monthly",
			"statistical_component": 1,
			"is_tax_applicable": 1,
			"is_basic_pay": 0,
			"is_13th_month_pay_applicable": 0,
			"depends_on_payment_days": 0,
		},
		{
			"name": "PH - HDMF Contribution",
			"salary_component": "PH - HDMF Contribution",
			"salary_component_abbr": "PH_HDMF",
			"type": "Deduction",
			"formula": "(0.01 * gross_pay)\n    if gross_pay <= 1500\n    else (150 if gross_pay >= 5000 else (0.02 * gross_pay))",
			"amount_based_on_formula": 1,
			"formula_based_on_attendance": 0,
			"formula_effectivity": "Monthly",
			"statistical_component": 0,
			"is_tax_applicable": 1,
			"is_basic_pay": 0,
			"is_13th_month_pay_applicable": 0,
			"depends_on_payment_days": 0,
		},
		{
			"name": "PH - HDMF Employer Contribution",
			"salary_component": "PH - HDMF Employer Contribution",
			"salary_component_abbr": "PH_HDMF_ER",
			"type": "Deduction",
			"formula": "(0.01 * gross_pay)\n    if gross_pay <= 1500\n    else (150 if gross_pay >= 5000 else (0.02 * gross_pay))",
			"amount_based_on_formula": 1,
			"formula_based_on_attendance": 0,
			"formula_effectivity": "Monthly",
			"statistical_component": 1,
			"is_tax_applicable": 1,
			"is_basic_pay": 0,
			"is_13th_month_pay_applicable": 0,
			"depends_on_payment_days": 0,
		},
		{
			"name": "PH - SSS Contribution",
			"salary_component": "PH - SSS Contribution",
			"salary_component_abbr": "PH_SSS",
			"type": "Deduction",
			"formula": "ph_sss(basic_pay)",
			"amount_based_on_formula": 1,
			"formula_based_on_attendance": 0,
			"formula_effectivity": "Monthly",
			"statistical_component": 0,
			"is_tax_applicable": 1,
			"is_basic_pay": 0,
			"is_13th_month_pay_applicable": 0,
			"depends_on_payment_days": 0,
		},
		{
			"name": "PH - SSS Employer Contribution",
			"salary_component": "PH - SSS Employer Contribution",
			"salary_component_abbr": "PH_SSS_ER",
			"type": "Deduction",
			"formula": "ph_sss_er(basic_pay)",
			"amount_based_on_formula": 1,
			"formula_based_on_attendance": 0,
			"formula_effectivity": "Monthly",
			"statistical_component": 1,
			"is_tax_applicable": 1,
			"is_basic_pay": 0,
			"is_13th_month_pay_applicable": 0,
			"depends_on_payment_days": 0,
		},
		{
			"name": "PH - SSS Employee Compensation",
			"salary_component": "PH - SSS Employee Compensation",
			"salary_component_abbr": "PH_SSS_EC",
			"type": "Deduction",
			"formula": "ph_sss_ec(basic_pay)",
			"amount_based_on_formula": 1,
			"formula_based_on_attendance": 0,
			"formula_effectivity": "Monthly",
			"statistical_component": 1,
			"is_tax_applicable": 1,
			"is_basic_pay": 0,
			"is_13th_month_pay_applicable": 0,
			"depends_on_payment_days": 0,
		},
		{
			"name": "PH - Withholding Tax",
			"salary_component": "PH - Withholding Tax",
			"salary_component_abbr": "PH_WTAX",
			"type": "Deduction",
			"formula": "ph_wtax()",
			"amount_based_on_formula": 1,
			"formula_based_on_attendance": 0,
			"formula_effectivity": "Monthly",
			"statistical_component": 0,
			"is_tax_applicable": 0,
			"is_basic_pay": 0,
			"is_13th_month_pay_applicable": 0,
			"depends_on_payment_days": 0,
		},
	]